### ISSUE TITLE
Character / Graphemes count seems to be inaccurate

### ISSUE THREAD

**Issue by jguadagno** [blowdart/idunno.Bluesky#42]
# Bug report 

### Describe the bug

I've been trying to post using both the `Post(string)` and `Post(PostBuilder)` methods and the count for the `PostBuilder` overload is failing stating that the message is over the Graphemes limit of three hundred.  It looks like the library is just the number of characters (I don't know how to count a Grapheme).  When the code is counting the characters, it uses the `text` property which contains the 'facets' as part it.

### Expected behavior

If I post the following message using the `Post(string)`

> ICYMI: (07/12/2024): "My JetBrains Rider Plugins — July 2024 Edition" RPs and feedback are always appreciated! https://jjg.me/3LmnPiF #JetBrains #Plugin #presenting #Rider

It comes in as 171 characters but just shows as plain text.

If I post the following using the `Post(PostBuilder)`, the library throws an exception for exceeding the Graphemes count.

```csharp
const string message = "ICYMI: (06/12/2020): \"Protecting an ASP.NET Core Web API with Microsoft Identity Platform.\" RPs and feedback are always appreciated! ";
var postBuilder = new PostBuilder(message);
const string url = "https://www.josephguadagno.net/2020/06/12/protecting-an-asp-net-core-api-with-microsoft-identity-platform";
const string shortenedUrl = "https://jjg.me/30xE7PA";
var hashTags = new List<string>
{
    "Azure", "Identity", "WebAPI", "MSAL", "ManagedIdentity", "Entra"
};

postBuilder.Append(" " + new Link(shortenedUrl, shortenedUrl));

foreach (var hashtag in hashTags)
{
    postBuilder.Append(" " + new HashTag(hashtag));
}
    
// Act
var response = await _blueskyManager.Post(postBuilder);
```

### Actual behavior

I would expect the `Post(PostBuilder)` to not count the "metadata" in the character count.

### What operating system(s) are you using?

- [X] Windows
- [ ] macOS
- [ ] Ubuntu
- [ ] Other Linux
- [ ] Other (specify below)

### Reproduction code

All the tests in this [project](https://github.com/jguadagno/jjgnet-broadcast/tree/main/src/JosephGuadagno.Broadcasting.Managers.Bluesky.Tests) that use `Post(PostBuilder)` fail.

**Comment by blowdart** [comment]
Well there were two problems

1) Links shouldn't have had a text or grapheme check all their own. That's not in the definition, I must have just cut/pasted the mention facet code as a starting point. That's now removed

2) The documentation is wrong. 

```c#
postBuilder.Append(" " + new HashTag(hashtag));
```

This won't work, because C# will just take that initial space as a string, then ToString() the hash tag, which is why you saw what you saw.

Updating the docs to reflect this and warn.

I'm half tempted to be a bad person and throw exceptions on ToString() in facets, but oh boy do I get lots of analyser warnings if I do. I'll reconsider that if this bites lots of people.

**Comment by blowdart** [comment]
v0.1.2 with the fix is now on [nuget](https://www.nuget.org/packages/idunno.Bluesky/0.1.2-prerelease)
